# Questions to include in the alerts
# All questions in these projects will be included
projects:
  - 1426
# All questions below will be included
questions:
  - 2534
  - 2797
  - 8366
  - 8855
  - 9743
  - 9969
  - 10008

# After fetching all questions above, the ones that don't meet these criteria will be excluded
# If a question meets all criteria except minimum_hours, then a "New question" alert is sent
filters:
  minimum_hours: 48 # Minimum number of hours since publishing
  minimum_forecasts: 10 # Minimum number of forecasts made
  types: # Types of questions handled by the bot
    - binary
  no_duplicate_period: 24 # Number of hours during which a question will be ignored after an alert

# Change thresholds (when at least 1 of these is true, a tweet will be sent)
# - absolute change of >5% in the last 5 hours
# - absolute change of >10% in the last 24 hours
thresholds:
  - hours: 5
    swing: 0.05
  - hours: 24
    swing: 0.1
