# Questions to include in the alerts
# All questions in these projects will be included
projects:
  - 1007 # Nuclear Risk Tournament
  - 1173 # Nuclear Risk Horizons Project
  - 1426 # Ukraine Conflict
  - 1683 # Monkeypox
  - 1703 # Biosecurity Tournament
# All questions below will be included
questions:
  - 1494 # GC to be caused by nuclear war, if it occurs?
  - 2534 # World War Three before 2050
  - 2797 # No Non-Test Nuclear Detonations by 2024
  - 3150 # No Non-Test Nuclear Detonations before 2035
  - 4779 # At least 1 Nuclear Detonation in War by 2050 
  - 8366 # Countries With 1+ Fatality From Nuclear Det.
  - 8855 # Major Agriculture Export Bans by 2023-04
  - 9743 # Zelenskyy Remains President of UA by 2023
  - 9969 # Chinese involvement in Ukrainian conflict
  - 10008 # Moldovan-Romanian union by 2025
  - 12591 # Nuclear Detonation in Ukraine by 2023

# After fetching all questions above, the ones that don't meet these criteria will be excluded
# If a question meets all criteria except minimum_hours, then a "New question" alert is sent
filters:
  minimum_hours: 48 # Minimum number of hours since publishing
  minimum_forecasts: 10 # Minimum number of forecasts made
  types: # Types of questions handled by the bot
    - binary
    - continuous
  no_duplicate_period: 24 # Number of hours during which a question will be ignored after an alert

# Change thresholds (when at least 1 of these is true, a tweet will be sent)
# - absolute change of >5% in the last 5 hours
# - absolute change of >10% in the last 24 hours
thresholds:
  - hours: 24
    swing: 0.1
    swing_continuous: 0.5
  - hours: 48
    swing: 0.2
    swing_continuous: 1
